### ISSUE TITLE
Disqus url incorrectly use double slash (//)

### ISSUE THREAD

**Issue by emmanuelbernard** [awestruct/awestruct#26]
Disqus module incorrectly creates link back in the form `http://example.com//my/commented/page`

**Comment by Oyyko** [comment]
Hi. May I ask you how to fix this problem? Since my website meet the same problem. Thanks.

**Comment by zbynek** [comment]
The fix for this was pushed 10 years ago https://github.com/awestruct/awestruct/commit/a5a3d2695f6d243134120b5e7f4dd97ea1020a3a -- @Oyyko what version of Awestruct are you using?
