### ISSUE TITLE
Store Asciidoctor::Document object in page context

### ISSUE THREAD

**Issue by mojavelinux** [awestruct/awestruct#288]
When rendering an AsciiDoc document using Asciidoctor, Awestruct should expose the Asciidoctor::Document object via the page context. This change will allow the layout to access information from the document for populating the sidebar, or other portions of the layout, with information such as the table of contents, list of links, list of figures, etc.

**Comment by rtyler** [comment]
@mojavelinux This is something that would be incredibly useful for our (Jenkins) new awestruct/asciidoctor deployment. Got a working prototype somewhere I can pull into our project and experiment with?

Monkeypatching doesn't scurr me :)

**Comment by LightGuard** [comment]
You could do this in an extension of you don't mind parsing the document
twice (asciidoctor is fast enough it shouldn't matter).

On Thursday, March 3, 2016, R. Tyler Croy <notifications@github.com> wrote:

> @mojavelinux <https://github.com/mojavelinux> This is something that
> would be incredibly useful for our (Jenkins) new awestruct/asciidoctor
> deployment. Got a working prototype somewhere I can pull into our project
> and experiment with?
>
> Monkeypatching doesn't scurr me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/288#issuecomment-191928476>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
It's a simple one-line change to make the document available as a variable in the context of the page. In our custom Tilt handler for AsciiDoc, change the contents of the evaluate method to the following:

```
@output ||= (scope.document = ::Asciidoctor.load data, options).convert
```

Then you can access the document from the page using the `document` variable. For example:

```
=document.doctitle
```

**Comment by Mogztter** [comment]
Pull request sent! :smile:
