### ISSUE TITLE
allow variables in site.yml

### ISSUE THREAD

**Issue by maxandersen** [awestruct/awestruct#292]
with github pages deploy it would be nice to be able to something like this in config.yml:

 ghpages:
    base_url: http://{env[$GITHUB_USER]}.github.com/jbosstools-website
    deploy:
      host: github_pages
      repository: {env[$GITHUB_USER]}
      branch: gh-pages

Could also add specific support for this "use github_user env variable" to ghpages deploy but it seems useful to have this for other than thus githubpages deployment.

**Comment by LightGuard** [comment]
This was fixed by allowing you to use ERB in the yaml file.

**Comment by maxandersen** [comment]
got an example of how that looks like ?

**Comment by LightGuard** [comment]
https://github.com/redhat-developer/developers.redhat.com/blob/master/_config/site.yml#L69

**Comment by maxandersen** [comment]
okey - but when I try latest awestruct it breaks jbosstools-website ...bummer ;/

i'll open seperate issue for that.
