### ISSUE TITLE
Create a Rake task to run a script before / after a build

### ISSUE THREAD

**Issue by LightGuard** [awestruct/awestruct#338]
This is the follow-up issue for #248, because we decided this was better done as a rake task.

**Comment by LightGuard** [comment]
Still worth doing or not?

**Comment by mojavelinux** [comment]
It seems to me like something that should be handled by the user in the custom way. For instance, Travis already provides these hooks, so if it's a CI thing, that's covered.

**Comment by LightGuard** [comment]
Sounds good to me. I'll go ahead and close then.
