### ISSUE TITLE
auto compile broken for scss

### ISSUE THREAD

**Issue by tcurdt** [awestruct/awestruct#417]
Change detected for file /.../assets/css/site.scss
    While processing file /.../assets/css/site.scss
    An error occurred: Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
    Run "compass -h" to get help.
    /Users/tcurdt/.gem/ruby/2.1.1/gems/compass-0.12.5/lib/compass/commands/update_project.rb:53:in `check_for_sass_files!'
    /Users/tcurdt/.gem/ruby/2.1.1/gems/compass-0.12.5/lib/compass/commands/update_project.rb:43:in `perform'
    /Users/tcurdt/Projects/awestruct/lib/awestruct/cli/auto.rb:49:in `block (3 levels) in run'

**Comment by LightGuard** [comment]
@tcurdt Could you try my master branch: LightGuard/awestruct and see if your setup using libsass (no compass in your project) and let me know please.

**Comment by LightGuard** [comment]
The generate on access feature may work for you too

**Comment by LightGuard** [comment]
There's now an option to use sassc in master, does that work for you? compass and sass are no longer required.

**Comment by LightGuard** [comment]
Somewhere along the way this was fixed, not really sure where, but I've added another css file to a site at the same location you have @tcurdt and it picked up the changes just fine.
