### ISSUE TITLE
ImpossibleDependenciesError on installing gem

### ISSUE THREAD

**Issue by niels-s** [awestruct/awestruct#423]
When I try to install the latest awestruct gem I got a ImpossibleDependenciesError. There are some conflicts in the dependencies. Awestruct requires mime-types ~> 2.1 but other direct dependencies of Awestruct rest-client-1.6.8, depends on an older version ~> 1.16.

Bumping the version of rest-client to 1.7.2 should do the trick I guess.

ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
    awestruct-0.5.5 requires mime-types (~> 2.1) but it conflicted:
  Activated mime-types-2.3 instead of (~> 1.16) via:
    rest-client-1.6.8, awestruct-0.5.5

I tried to build the gem locally but got this error (unrelated to bumping the rest-client version, tried to build both master and with the new rest-client version. same result):

```
/workspace/awestruct/lib/awestruct/engine.rb:20:in `require': cannot load such file -- parallel (LoadError)
from /workspace/awestruct/lib/awestruct/engine.rb:20:in `<top (required)>'
from /workspace/awestruct/spec/support/shared_handler_example.rb:1:in `require'
from /workspace/awestruct/spec/support/shared_handler_example.rb:1:in `<top (required)>'
from /workspace/awestruct/spec/spec_helper.rb:4:in `require'
from /workspace/awestruct/spec/spec_helper.rb:4:in `block in <top (required)>'
from /workspace/awestruct/spec/spec_helper.rb:4:in `each'
from /workspace/awestruct/spec/spec_helper.rb:4:in `<top (required)>'
from /workspace/awestruct/spec/awestruct/cli/init_spec.rb:1:in `require'
from /workspace/awestruct/spec/awestruct/cli/init_spec.rb:1:in `<top (required)>'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
from .rvm/gems/ruby-2.1.2/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by purplefox** [comment]
Anyone got any idea how to fix this? I am trying to install awestruct on a clean machine and hitting the same issue:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: awestruct requires mime-types (~> 2.1); rest-client requires mime-types (~> 1.16)

**Comment by eschabell** [comment]
Same here still a problem... breaks OpenShift ruby 1.9 awestruct usage too...

**Comment by LightGuard** [comment]
I have an idea on how to fix it, bear with me for a week?

On Sun, Feb 8, 2015 at 4:29 AM, Eric D. Schabell <notifications@github.com>
wrote:

> Same here still a problem... breaks OpenShift ruby 1.9 awestruct usage
> too...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/423#issuecomment-73406967>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by eschabell** [comment]
Sure thing! ;)

**Comment by LightGuard** [comment]
I was looking at removing rest-client and mime-types, but all of the 0.5.6.beta versions have updated dependencies. Please try using that version (you'll need to install with gem --pre, or just using the exact version in bundler) and let me know if this still exists or if other issues are there.

**Comment by aeggum12** [comment]
I saw the same error message as purplefox when doing a regular install after a fresh install of ruby (v1.9.3).

Trying the install with a beta version, I get the following:

    sudo gem install awestruct -v 0.5.6.beta8 
       Building native extensions.  This could take a while...
        ERROR:  Error installing awestruct:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
     /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf        (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'


    Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.6 for inspection.
    Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.6/ext/ffi_c/gem_make.out

I haven't used ruby in a while, could I be doing something wrong?

**Comment by LightGuard** [comment]
mkmf.... Not sure what that one is, I'll have to dig.

On Fri, Feb 13, 2015 at 12:32 PM, Adam Eggum <notifications@github.com>
wrote:

> I saw the same error message as purplefox when doing a regular install
> after a fresh install of ruby (v1.9.3).
>
> Trying the install with a beta version, I get the following:
>
> sudo gem install awestruct -v 0.5.6.beta8
>    Building native extensions.  This could take a while...
>     ERROR:  Error installing awestruct:
> ERROR: Failed to build gem native extension.
>
>     /usr/bin/ruby1.9.1 extconf.rb
>  /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf        (LoadError)
> from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
> from extconf.rb:4:in `<main>'
>
>
> Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.6 for inspection.
> Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.6/ext/ffi_c/gem_make.out
>
> I haven't used ruby in a while, could I be doing something wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/423#issuecomment-74312197>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by aeggum12** [comment]
The mkmf issue appears to have been on my end.  I needed the ruby-dev package: http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror

    sudo apt-get install ruby-dev

After that was installed, I could gem install the beta version, and it appears to be installed correctly.   Sorry for the false alarm!

**Comment by LightGuard** [comment]
No problem.

On Fri, Feb 13, 2015 at 12:45 PM, Adam Eggum <notifications@github.com>
wrote:

> The mkmf issue appears to have been on my end. I needed the ruby-dev
> package:
> http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror
>
> sudo apt-get install ruby-dev
>
> After that was installed, I could gem install the beta version, and it
> appears to be installed correctly. Sorry for the false alarm!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/423#issuecomment-74314523>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by eschabell** [comment]
works for me now locally and on openshift, site generation is a bit off but can investigate that separately.
