### ISSUE TITLE
interpolate is false by default

### ISSUE THREAD

**Issue by jmesnil** [awestruct/awestruct#429]
I upgraded my website from 0.5.3 to 0.5.5 and noticed that all Ruby strings in my `*.md` file were no longer working.

After some debugging, it turns out that String interpolation is `false` now by default which broke my code.
I fixed it by setting up `interpolate: true` in my `_config/site.yml`.

I'm not sure whether it's a regression but if interpolation is disabled, the [file types doc](http://awestruct.org/file_types/) should be updated to reflect that when the awestruct.org is updated for 0.5.5 release

**Comment by LightGuard** [comment]
Fixed with awestruct/awestruct.org@ebae5e1afb32a228a1aaf561431a7cbd9f499256

**Comment by jmtd** [comment]
I think that change has the logic backwards: you need to set it to true to enable, not to false, which is the default anyway. I've swapped it in PR #69.

**Comment by LightGuard** [comment]
It's correct that it is disabled by default now, I know the docs need
updating, there's an issue for it :)

You turn it on at the site level by setting interpolate to true in the
site.yml or you can set it to true at the page level in the front matter of
each page needing it. We've found having it always enabled has resulted in
some issue with some content, plus it's also much faster to not check every
line in the site for the interpolated text.

On Thursday, October 8, 2015, Jonathan Dowland <notifications@github.com>
wrote:

> I think that change has the logic backwards: you need to set it to true to
> enable, not to false, which is the default anyway. I've swapped it in PR
> #69 <https://github.com/awestruct/awestruct/issues/69>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/429#issuecomment-146544462>
> .
>


-- 
Sent from Gmail Mobile
