### ISSUE TITLE
Build error on Atom feed

### ISSUE THREAD

**Issue by xcoulon** [awestruct/awestruct#446]
Using awestruct-0.5.6.Beta7, I get this error:

    <h1>#<REXML::ParseException: Missing end tag for 'br' (got "p")
    Line: 6
    Position: 679
    Last 80 unconsumed characters:
    >
    /Users/xcoulon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:335:in `pull_event'
    /Users/xcoulon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull'
    /Users/xcoulon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse'
    /Users/xcoulon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rexml/document.rb:245:in `build'
    /Users/xcoulon/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/context_helper.rb:42:in `new'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/context_helper.rb:42:in `fully_qualify_urls'
    atom.template.haml:41:in `block (2 levels) in singletonclass'
    atom.template.haml:20:in `each'
    atom.template.haml:20:in `block in singletonclass'
    atom.template.haml:65529:in `instance_eval'
    atom.template.haml:65529:in `singletonclass'
    atom.template.haml:65527:in `__tilt_2155915220'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/page.rb:143:in `rendered_content'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/engine.rb:361:in `generate_page'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/engine.rb:349:in `block in generate_output'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:430:in `call'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:430:in `call_with_index'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:334:in `process_incoming_jobs'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:316:in `block in worker'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:309:in `fork'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:309:in `worker'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:297:in `block in create_workers'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:296:in `each'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:296:in `create_workers'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:253:in `work_in_processes'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:191:in `map'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/parallel-1.3.3/lib/parallel.rb:152:in `each'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/engine.rb:346:in `generate_output'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/engine.rb:81:in `run'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/cli/generate.rb:21:in `run'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/cli/invoker.rb:125:in `invoke_generate'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/lib/awestruct/cli/invoker.rb:49:in `invoke!'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/gems/awestruct-0.5.6.beta7/bin/awestruct:9:in `<top (required)>'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/bin/awestruct:23:in `load'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/bin/awestruct:23:in `<main>'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/bin/ruby_executable_hooks:15:in `eval'
    /Users/xcoulon/.rvm/gems/ruby-1.9.3-p547@jbosstools-website/bin/ruby_executable_hooks:15:in     `<main>'
    ...
    Missing end tag for 'br' (got "p")
    Line: 6
    Position: 679

**Comment by maxandersen** [comment]
I don't see this go away even with :backend: xhtml5 with beta8 and jbosstools-website.

works fine with stable awestruct.

**Comment by maxandersen** [comment]
the issue is btw. inside fully_qualify_urls that seem to not be able to handle as much xml as it could before.

**Comment by maxandersen** [comment]
okey - isolated this to what looks like bugs in asciidoctors xhtml mode.
i.e.

```link:http://docs.jboss.com/jbpm/v3.2/userguide/html_single/"[jBPM3]```

got translated into:

```<a href="http://docs.jboss.com/jbpm/v3.2/userguide/html_single/"">jBPM3]</a>```

notice the double quotes.

**Comment by maxandersen** [comment]
btw. I would argue awestruct still have a bug in that 

"= clean_html( html_escape( fully_qualify_urls( site.base_url, find_and_preserve( entry.content ) ) ) )"

in atom.template.haml still need to be changed to something like:

"= clean_html( html_escape( fully_qualify_urls( site.base_url, find_and_preserve( "<div>#{entry.content}</div>" ) ) ) )"

to work.

otherwise you will get the error of multiple elements being added to the same root.

**Comment by xcoulon** [comment]
Reopening after @maxandersen's comment above

**Comment by LightGuard** [comment]
This is probably related to switching away from Nokogiri to REXML.
@mojavelinx had another xml parser to look at, I just haven't been able to
follow up with him yet.

On Tue, Jan 27, 2015 at 5:58 AM, Xavier Coulon <notifications@github.com>
wrote:

> Reopening after @maxandersen <https://github.com/maxandersen>'s comment
> above
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/446#issuecomment-71643752>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
yes nokogiri to rexml makes the error visible with a hard stop/crash.

But the atom feed is not generating proper xml without this fix as long as the content is not being nested.

so that might be worth fixing no matter if using nokogiri or rexml

**Comment by LightGuard** [comment]
Does this just need a fix to the atom template?

**Comment by maxandersen** [comment]
Well, my suggested fix is more a higher level fix for the underlying problem that the xml generated/passed up is not considered valid by rexml.

**Comment by maxandersen** [comment]
Looking more into this then i'm coming to the conclusion that this will just keep failing as long as you have html (not xhtml) posts which use more lax html syntax.

Something I have in about ~80+ blog posts converted from wordpress to .erb/html. 

Is there a way to get a non-strict html parser included for use for atom feed instead of REXML which will just keep failing ?

**Comment by maxandersen** [comment]
This change is what breaks it: https://github.com/awestruct/awestruct/commit/f0259ca13cff36fec3099d8e894e764a44228dbc#diff-4a7e03e9ea98913a60caa974b4b92a99R1

**Comment by LightGuard** [comment]
Looking into something that should help.

On Sunday, April 5, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> This change is what breaks it: f0259ca
> #diff-4a7e03e9ea98913a60caa974b4b92a99R1
> <https://github.com/awestruct/awestruct/commit/f0259ca13cff36fec3099d8e894e764a44228dbc#diff-4a7e03e9ea98913a60caa974b4b92a99R1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/446#issuecomment-89869897>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
with #460 and with syntax fixes in my .erb files this is now working on both xam.dk and jbosstools website.

**Comment by LightGuard** [comment]
Is that a :+1: to merge?

On Wed, Apr 8, 2015 at 12:58 AM, Max Rydahl Andersen <
notifications@github.com> wrote:

> with #460 <https://github.com/awestruct/awestruct/pull/460> and with
> syntax fixes in my .erb files this is now working on both xam.dk and
> jbosstools website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/446#issuecomment-90824172>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
+1

**Comment by LightGuard** [comment]
Care to test https://github.com/awestruct/awestruct/pull/467 for me, see if that helps?
