### ISSUE TITLE
Minified files are not published with bootstrap community theme and awestruct 0.5.6beta7

### ISSUE THREAD

**Issue by xcoulon** [awestruct/awestruct#449]
When the minification is enabled on the JBoss.org bootstrap community theme (https://github.com/jbossorg/bootstrap-community), eg:
````
bundle exec awestruct -P production
````
the .js and .css files are minified and stored in a _tmp folder and new pages are added to the site (as shown in https://github.com/jbossorg/bootstrap-community/blob/master/_ext/css_minifier.rb#L74), but at the end, nothing is copied in the _site target folder, which results is css and js not loaded in the browser because of 404 errors :(

**Comment by maxandersen** [comment]
this also happens in beta8.

only difference being moving from 0.5.5 to 0.5.6.beta8 in Gemfile.

**Comment by LightGuard** [comment]
Is this a problem with awestruct or the JBoss supplied community build?
They've done some really weird stuff with that base.

On Mon, Jan 26, 2015 at 4:32 PM, Max Rydahl Andersen <
notifications@github.com> wrote:

> this also happens in beta8.
>
> only difference being moving from 0.5.5 to 0.5.6.beta8 in Gemfile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/449#issuecomment-71561295>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
I use awestruct - I don't use a jboss supplied build.

Do you mean the awestruct project I use ? Then yes, its based off jboss.org template + our modifications.

**Comment by maxandersen** [comment]
okey so I looked into this - I got good and bad news.

Bad news:
There is clearly a behavioral change from old awestruct to new when it comes to how transform'ers are handled. In old you could add additional pages to the output using code like this: 

```
     # Add the temporary file to the list of pages for rendering phase.
        newPage = site.engine.load_page(tmpOutputPath)
        newPage.source_path = tmpOutputPath
        newPage.output_path = newOutputPath
        site.pages << newPage
```

That works in 0.5.5, but seem to be ignored in master. 
This is what is used in community minifications: https://github.com/jbossorg/bootstrap-community/blob/master/_ext/css_minifier.rb#L74

So it would be good to either still support this or we need find a fix for this that everyone can consume somewhat easily.

Good news:
I've updated the minification code in jbosstools-website to simply just minify in-place instead of generating new files as a workaround to this issue.
See example here: https://github.com/jbosstools/jbosstools-website/pull/375/files#diff-42dbfb06ba7b36c4506096a839c04721L60

**Comment by maxandersen** [comment]
to be clear - it is not a trivial change to update to this since the layouts need to be adjusted too to not use .min.js/.min.css etc. 

So best solution would be to support transform as it worked in old versions or provide some docs to know how to add add files in a transform.

**Comment by LightGuard** [comment]
Is there a reason you don't just minify it and reuse the name of the file??

I could think of a few ways to fix the base and not have it be all crazy, but that doesn't make migration that much easier for you.

**Comment by maxandersen** [comment]
This is not *my* code, its the code from jboss community base awestruct example.
I can tell my theory for why its not minifying in-place is that jboss community site points to static generated resources and there is  a pattern of toggling between file.js and file.min.js depending on a flag.

thus my guess is they repeated this in their minifiers for consistency sake.

Do we know the reason for why this code stopped working ?
Is there a fix to these that could make it work for both 0.5.5 and newer awestruct versoins ?

Then I could at least make PR against the community site so others have a place to update from when doing migration.

Important to remember this change wont affect just me - it will affect anyone that used the .org community awestruct base which is a good bunch by now unfortunately.

**Comment by LightGuard** [comment]
Are we better now with HEAD?

On Thu, Apr 9, 2015 at 3:19 AM, Max Rydahl Andersen <
notifications@github.com> wrote:

> This is not *my* code, its the code from jboss community base awestruct
> example.
> I can tell my theory for why its not minifying in-place is that jboss
> community site points to static generated resources and there is a pattern
> of toggling between file.js and file.min.js depending on a flag.
>
> thus my guess is they repeated this in their minifiers for consistency
> sake.
>
> Do we know the reason for why this code stopped working ?
> Is there a fix to these that could make it work for both 0.5.5 and newer
> awestruct versoins ?
>
> Then I could at least make PR against the community site so others have a
> place to update from when doing migration.
>
> Important to remember this change wont affect just me - it will affect
> anyone that used the .org community awestruct base which is a good bunch by
> now unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/449#issuecomment-91171103>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
This is the last coding issue I have for 0.5.6, and I need one of you two (@maxandersen or @xcoulon) to verify this works on HEAD.

**Comment by maxandersen** [comment]
I rolled back jbosstools-website to use the the _ext code before my fix and with this and HEAD of awestruct I still do not see the actual files being generated into the _site.

Thus if the expectation is that jboss.org awestruct sites will continue to work as-is after this update than No, HEAD does not seem to fix that.

**Comment by LightGuard** [comment]
Hrm, how can I test this? Do I need to deploy or can I do this with a gen
in the production profile?

On Monday, April 27, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> I rolled back jbosstools-website to use the the _ext code before my fix
> and with this and HEAD of awestruct I still do not see the actual files
> being generated into the _site.
>
> Thus if the expectation is that jboss.org awestruct sites will continue
> to work as-is after this update than No, HEAD does not seem to fix that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/449#issuecomment-96573393>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
maxandersen/jbosstools-website minifybroken branch (https://github.com/maxandersen/jbosstools-website/tree/minifybroken) has the _ext/*minify* checked out with the version that worked with previous awestruct.

When checked out run:

`bundle exec awestruct -P production -g --force`

and notice how _site/stylesheets and _site/javascript are *missing* .min.js files. If this worked all of them would have matching .min. files, not only those that are preminified.

**Comment by LightGuard** [comment]
Please see https://github.com/maxandersen/jbosstools-website/pull/5 for the necessary changes to work with HEAD.

**Comment by LightGuard** [comment]
There is a migration needed, you can see the steps in the previous comment that need to be taken.
