### ISSUE TITLE
Upgrade to nokogiri 1.6 so "rake setup" for a awestruct site just works (instead of failing on nokogiri 1.5)

### ISSUE THREAD

**Issue by ge0ffrey** [awestruct/awestruct#454]
From the nokogiri website "As of Nokogiri 1.6, libxml2 and libxslt source code is bundled with Nokogiri, and compiled at gem-install-time."
This means it's a much less pita as of version 1.6 :)

**Comment by LightGuard** [comment]
I want to do away with Nokogiri all together.

On Monday, February 2, 2015, Geoffrey De Smet <notifications@github.com>
wrote:

> From the nokogiri website "As of Nokogiri 1.6, libxml2 and libxslt source
> code is bundled with Nokogiri, and compiled at gem-install-time."
> This means it's a much less pita as of version 1.6 :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/454>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by ge0ffrey** [comment]
Whatever takes the "libXml2 is not installed" pain away is very welcome :)
Trying to build my site on a secondary computer and running into this pain
again.
Also trying to convince some of my colleague's to build the site
themselves, but they are also running into setup issues (mostly related to
having ruby 2 instead of ruby 1.9 installed by default), so they don't
build the sites...

2015-02-02 22:27 GMT+01:00 Jason Porter <notifications@github.com>:

> I want to do away with Nokogiri all together.
>
> On Monday, February 2, 2015, Geoffrey De Smet <notifications@github.com>
> wrote:
>
> > From the nokogiri website "As of Nokogiri 1.6, libxml2 and libxslt
> source
> > code is bundled with Nokogiri, and compiled at gem-install-time."
> > This means it's a much less pita as of version 1.6 :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/awestruct/awestruct/issues/454>.
> >
>
>
> --
> Jason Porter
> http://en.gravatar.com/lightguardjp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/454#issuecomment-72541412>.
>



-- 
With kind regards / Met vriendelijke groeten,
Geoffrey De Smet

**Comment by LightGuard** [comment]
I hear you. That's the biggest reason for dropping nokogiri.

On Tuesday, February 3, 2015, Geoffrey De Smet <notifications@github.com>
wrote:

> Whatever takes the "libXml2 is not installed" pain away is very welcome :)
> Trying to build my site on a secondary computer and running into this pain
> again.
> Also trying to convince some of my colleague's to build the site
> themselves, but they are also running into setup issues (mostly related to
> having ruby 2 instead of ruby 1.9 installed by default), so they don't
> build the sites...
>
> 2015-02-02 22:27 GMT+01:00 Jason Porter <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > I want to do away with Nokogiri all together.
> >
> > On Monday, February 2, 2015, Geoffrey De Smet <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > From the nokogiri website "As of Nokogiri 1.6, libxml2 and libxslt
> > source
> > > code is bundled with Nokogiri, and compiled at gem-install-time."
> > > This means it's a much less pita as of version 1.6 :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/awestruct/awestruct/issues/454>.
> > >
> >
> >
> > --
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/awestruct/awestruct/issues/454#issuecomment-72541412>.
>
> >
>
>
>
> --
> With kind regards / Met vriendelijke groeten,
> Geoffrey De Smet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/454#issuecomment-72609918>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
Fixed by #460
