### ISSUE TITLE
looking for i18n examples

### ISSUE THREAD

**Issue by ryanj** [awestruct/awestruct#455]
Hello, I'm using awestruct to build the [OpenShift Developer Center](https://developers.openshift.com/).

We've recently had some questions about [i18n / L10N with awestruct](https://github.com/openshift/devcenter/issues/227).  

I'm looking for:
* [ ] links to example implementations that include i18n / L10n (if you are aware of any)

Our repo currently stores the majority of our site content under an "en" folder, and I'll need to make a few updates to the templates (_layouts) to filter the menu listings.

It doesn't look like asciidoc and getText will mix well.  I've also run into several strange build errors when processing files that include special characters.  I'm worried that international characters might break our build.  Let me know if you have any tips on avoiding 'high ascii' build failures.

Thanks!

**Comment by LightGuard** [comment]
Look at the arquillian site, they've done some i18n. Which version of ruby
and awestruct are you using? Current ruby and current awestruct shouldn't
have any problem with unicode.

On Tue, Feb 3, 2015 at 12:43 PM, ryan jarvinen <notifications@github.com>
wrote:

> Hello, I'm using awestruct to build the OpenShift Developer Center
> <https://developers.openshift.com/>.
>
> We've recently had some questions about i18n / L10N with awestruct
> <https://github.com/openshift/devcenter/issues/227>.
>
> I'm looking for:
>
>    - [] links to example implementations that include i18n / L10n (if you
>    are aware of any)
>
> Our repo currently stores the majority of our site content under an "en"
> folder, and I'll need to make a few updates to the templates (_layouts) to
> filter the menu listings.
>
> It doesn't look like asciidoc and getText will mix well. I've also run
> into several strange build errors when processing files that include
> special characters. I'm worried that international characters might break
> our build. Let me know if you have any tips on avoiding 'high ascii' build
> failures.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/455>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by ryanj** [comment]
Thanks for your help!
