### ISSUE TITLE
awestruct -d fails silently if port already in use

### ISSUE THREAD

**Issue by maxandersen** [awestruct/awestruct#463]
```
cd website
bundle exec awestruct -d
```
see it run and server content.
switch to another terminal and run the same command.

Now awestruct just silently exits - without telling it stopped because port is already used.

In previous versions awestruct would print out stack trace with that info.

**Comment by LightGuard** [comment]
I'm now receiving:

```
Running command: bundle exec awestruct -d
Using profile: development
Generating site: http://localhost:4242
Excecuting pipeline...
Build time: Tue, 14 Apr 2015 15:22:16 MDT
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
[2015-04-14 15:22:16] INFO  WEBrick 1.3.1
[2015-04-14 15:22:16] INFO  ruby 2.2.0 (2014-12-25) [x86_64-linux]
[2015-04-14 15:22:16] WARN  TCPServer Error: Address already in use - bind(2) for "0.0.0.0" port 4242
```

Can you confirm with HEAD?

**Comment by maxandersen** [comment]
Cannot confirm.
using `gem 'awestruct', :git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'` and running `bundle update` I still see awestruct silent exit when another awestruct is running on same port.

**Comment by LightGuard** [comment]
You don't see it at the end of the web brick info? Could you paste what you
are seeing please?

On Wednesday, April 15, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> Cannot confirm.
> using gem 'awestruct', :git => 'git://github.com/awestruct/awestruct.git',
> :branch => 'master' and running bundle update I still see awestruct
> silent exit when another awestruct is running on same port.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/463#issuecomment-93372113>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
one first run:

```
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
[2015-04-17 11:49:44] INFO  WEBrick 1.3.1
[2015-04-17 11:49:44] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
[2015-04-17 11:49:44] INFO  WEBrick::HTTPServer#start: pid=16735 port=4242
```

second run in separate terminal:

```
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
[2015-04-17 11:50:04] INFO  WEBrick 1.3.1
[2015-04-17 11:50:04] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
~/c/j/jbosstools-website git:production ❯❯❯
```

so nothing shown - seems to behave like before.

**Comment by LightGuard** [comment]
Interesting. I wonder if this is a change in ruby that happened in 2.2 or a
Mac thing. I'll have to try on ruby 2.2

On Friday, April 17, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> one first run:
>
> ***************************************************************************
> Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
> ***************************************************************************
> [2015-04-17 11:49:44] INFO  WEBrick 1.3.1
> [2015-04-17 11:49:44] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
> [2015-04-17 11:49:44] INFO  WEBrick::HTTPServer#start: pid=16735 port=4242
>
> second run in separate terminal:
>
> ***************************************************************************
> Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
> ***************************************************************************
> [2015-04-17 11:50:04] INFO  WEBrick 1.3.1
> [2015-04-17 11:50:04] INFO  ruby 2.2.1 (2015-02-26) [x86_64-darwin14]
> ~/c/j/jbosstools-website git:production ❯❯❯
>
> so nothing shown - seems to behave like before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/463#issuecomment-93954979>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
this is still just failing silently for me. Does not look fixed.

**Comment by LightGuard** [comment]
Really?? I even had a test for this.

On Monday, April 27, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> this is still just failing silently for me. Does not look fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/463#issuecomment-96573740>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
![screenshot from 2015-04-27 14 48 40](https://cloud.githubusercontent.com/assets/29971/7357518/82cb8c1a-ecec-11e4-997c-baa2510a9857.png)

I have no idea why this not is working for you @maxandersen but it is for me.
