### ISSUE TITLE
latest awestruct have issues with compass/bootstrap

### ISSUE THREAD

**Issue by maxandersen** [awestruct/awestruct#465]
https://github.com/maxandersen/jbosstools-website/tree/brokenawestruct uses head of awestruct and when run `rake preview` result in:

```
/Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/manifest.rb:1:in `require': cannot load such file -- sass/callbacks (LoadError)
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/manifest.rb:1:in `<top (required)>'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/init.rb:1:in `require'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/init.rb:1:in `<top (required)>'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/invoker.rb:34:in `require'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/lib/awestruct/cli/invoker.rb:34:in `initialize'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/bin/awestruct:8:in `new'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bundler/gems/awestruct-33415cb88876/bin/awestruct:8:in `<top (required)>'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bin/awestruct:23:in `load'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bin/awestruct:23:in `<main>'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bin/ruby_executable_hooks:15:in `eval'
	from /Users/max/.rvm/gems/ruby-2.2.1@jbosstools-website/bin/ruby_executable_hooks:15:in `<main>'
```

Notice how this is not errors in  the website but in awestruct itself. 

it goes away if I start requiring bootstrap and compass in the Gemfile, but that should not be necessary should it ?

**Comment by maxandersen** [comment]
confirmed! thanks ;)

**Comment by LightGuard** [comment]
Did the modification work too?

On Tuesday, April 14, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> confirmed! thanks ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/465#issuecomment-92758513>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
modification ? not sure what you mean.

What I tested was that with the commit referenced I could run rake preview without declaring sass dependency.

**Comment by LightGuard** [comment]
Sorry, meant minification

On Wednesday, April 15, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> modification ? not sure what you mean.
>
> What I tested was that with the commit referenced I could run rake preview
> without declaring sass dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/465#issuecomment-93225346>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
ill try minification when i'm back from pto - requires me to undo my fixes ;)
