### ISSUE TITLE
latest master breaks generation

### ISSUE THREAD

**Issue by maxandersen** [awestruct/awestruct#471]
this worked earlier today, now I reran bundle install and seeing this error:

```
[2015-04-27 23:43:24] INFO  WEBrick::HTTPServer#start: pid=6243 port=4242
Regenerate /Users/max/code/jbosstools/jbosstools-website/index.html.haml
[2015-04-27 23:43:28] ERROR ArgumentError: wrong number of arguments (3 for 1..2)
	/Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/engine.rb:372:in `generate_page'
	/Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/rack/generate.rb:37:in `call'
	/Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Do you want maybe add jbosstools-website in as an integration test ? :)

**Comment by maxandersen** [comment]
using commit b8ad2ea56a38839b44659d47d56ef338e69d8a88 works. Latest commit breaks.

**Comment by LightGuard** [comment]
Thanks. Looks like I have a path that isn't being tested, otherwise I would
have found this.

On Monday, April 27, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> this worked earlier today, now I reran bundle install and seeing this
> error:
>
> [2015-04-27 23:43:24] INFO  WEBrick::HTTPServer#start: pid=6243 port=4242
> Regenerate /Users/max/code/jbosstools/jbosstools-website/index.html.haml
> [2015-04-27 23:43:28] ERROR ArgumentError: wrong number of arguments (3 for 1..2)
>     /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/engine.rb:372:in `generate_page'
>     /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/rack/generate.rb:37:in `call'
>     /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
>     /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
>
> Do you want maybe add jbosstools-website in as an integration test ? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/471>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
I need to build some integration tests using real sites.

On Monday, April 27, 2015, Jason Porter <lightguard.jp@gmail.com> wrote:

> Thanks. Looks like I have a path that isn't being tested, otherwise I
> would have found this.
>
> On Monday, April 27, 2015, Max Rydahl Andersen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> this worked earlier today, now I reran bundle install and seeing this
>> error:
>>
>> [2015-04-27 23:43:24] INFO  WEBrick::HTTPServer#start: pid=6243 port=4242
>> Regenerate /Users/max/code/jbosstools/jbosstools-website/index.html.haml
>> [2015-04-27 23:43:28] ERROR ArgumentError: wrong number of arguments (3 for 1..2)
>>     /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/engine.rb:372:in `generate_page'
>>     /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/rack/generate.rb:37:in `call'
>>     /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
>>     /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
>>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
>>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
>>     /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
>>
>> Do you want maybe add jbosstools-website in as an integration test ? :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/awestruct/awestruct/issues/471>.
>>
>
>
> --
> Jason Porter
> http://en.gravatar.com/lightguardjp
>
>

-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
On 28 Apr 2015, at 0:35, Jason Porter wrote:

> I need to build some integration tests using real sites.

I offer mine ;)

jbosstools/jbosstools-websites
maxandersen/xam.dk

>
> On Monday, April 27, 2015, Jason Porter <lightguard.jp@gmail.com> 
> wrote:
>
>> Thanks. Looks like I have a path that isn't being tested, otherwise I
>> would have found this.
>>
>> On Monday, April 27, 2015, Max Rydahl Andersen 
>> <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> this worked earlier today, now I reran bundle install and seeing 
>>> this
>>> error:
>>>
>>> [2015-04-27 23:43:24] INFO  WEBrick::HTTPServer#start: pid=6243 
>>> port=4242
>>> Regenerate 
>>> /Users/max/code/jbosstools/jbosstools-website/index.html.haml
>>> [2015-04-27 23:43:28] ERROR ArgumentError: wrong number of arguments 
>>> (3 for 1..2)
>>>  
>>> /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/engine.rb:372:in 
>>> `generate_page'
>>>  
>>> /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/rack/generate.rb:37:in 
>>> `call'
>>>  
>>> /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in 
>>> `call'
>>>  
>>> /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in 
>>> `service'
>>>  
>>> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in 
>>> `service'
>>>  
>>> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in 
>>> `run'
>>>  
>>> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in 
>>> `block in start_thread'
>>>
>>> Do you want maybe add jbosstools-website in as an integration test ? 
>>> :)
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/awestruct/awestruct/issues/471>.
>>>
>>
>>
>> --
>> Jason Porter
>> http://en.gravatar.com/lightguardjp
>>
>>
>
> -- 
> Jason Porter
> http://en.gravatar.com/lightguardjp
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/awestruct/awestruct/issues/471#issuecomment-96839696


/max
http://about.me/maxandersen

**Comment by LightGuard** [comment]
Thanks, now to find an ready easy to add it to the test suite and modify
the Gemfile.

On Tuesday, April 28, 2015, Max Rydahl Andersen <notifications@github.com>
wrote:

> On 28 Apr 2015, at 0:35, Jason Porter wrote:
>
> > I need to build some integration tests using real sites.
>
> I offer mine ;)
>
> jbosstools/jbosstools-websites
> maxandersen/xam.dk
>
> >
> > On Monday, April 27, 2015, Jason Porter <lightguard.jp@gmail.com
> <javascript:_e(%7B%7D,'cvml','lightguard.jp@gmail.com');>>
> > wrote:
> >
> >> Thanks. Looks like I have a path that isn't being tested, otherwise I
> >> would have found this.
> >>
> >> On Monday, April 27, 2015, Max Rydahl Andersen
> >> <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> >> <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> >>
> >>> this worked earlier today, now I reran bundle install and seeing
> >>> this
> >>> error:
> >>>
> >>> [2015-04-27 23:43:24] INFO WEBrick::HTTPServer#start: pid=6243
> >>> port=4242
> >>> Regenerate
> >>> /Users/max/code/jbosstools/jbosstools-website/index.html.haml
> >>> [2015-04-27 23:43:28] ERROR ArgumentError: wrong number of arguments
> >>> (3 for 1..2)
> >>>
> >>>
> /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/engine.rb:372:in
>
> >>> `generate_page'
> >>>
> >>>
> /Users/max/.rvm/gems/ruby-2.2.1/bundler/gems/awestruct-a52f23feb8b7/lib/awestruct/rack/generate.rb:37:in
>
> >>> `call'
> >>>
> >>>
> /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in
> >>> `call'
> >>>
> >>>
> /Users/max/.rvm/gems/ruby-2.2.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in
>
> >>> `service'
> >>>
> >>>
> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in
>
> >>> `service'
> >>>
> >>>
> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in
>
> >>> `run'
> >>>
> >>>
> /Users/max/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in
> >>> `block in start_thread'
> >>>
> >>> Do you want maybe add jbosstools-website in as an integration test ?
> >>> :)
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <https://github.com/awestruct/awestruct/issues/471>.
> >>>
> >>
> >>
> >> --
> >> Jason Porter
> >> http://en.gravatar.com/lightguardjp
> >>
> >>
> >
> > --
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/awestruct/awestruct/issues/471#issuecomment-96839696
>
>
> /max
> http://about.me/maxandersen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/471#issuecomment-97073896>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp
