### ISSUE TITLE
Awestruct --init command in Getting Started fails

### ISSUE THREAD

**Issue by jaredmorgs** [awestruct/awestruct#475]
I just ran the suggested Awestruct command after getting Awestruct installed.

I get this result.

Any idea why I'm seeing this, and how I might fix it? 
```
[jmorgan@localhost jaredmorgs.github.io]$ awestruct --init --framework foundation
WARN: Unresolved specs during Gem::Specification.reset:
      bundler (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/jmorgan/.gem/ruby/gems/celluloid-0.17.0.pre15/lib/celluloid/deprecate.rb:13: warning: already initialized constant Celluloid::Logger
/home/jmorgan/.gem/ruby/gems/celluloid-essentials-0.20.0.pre17/lib/celluloid/essentials.rb:27: warning: previous definition of Logger was here
I, [2015-06-09T22:01:54.506475 #5731]  INFO -- : +--------------------------------------------------+
I, [2015-06-09T22:01:54.506552 #5731]  INFO -- : |    Celluloid version running now: 0.17.0.pre15   +
W, [2015-06-09T22:01:54.506590 #5731]  WARN -- : +--------------------------------------------------+
W, [2015-06-09T22:01:54.506617 #5731]  WARN -- : |     Celluloid is running in BACKPORTED mode.     |
W, [2015-06-09T22:01:54.506644 #5731]  WARN -- : |   Time to update deprecated code, before v1.0!   |
W, [2015-06-09T22:01:54.506659 #5731]  WARN -- : +--------------------------------------------------+
W, [2015-06-09T22:01:54.506676 #5731]  WARN -- : |  Prepare! As of v0.17.5 you can begin updating.  |
W, [2015-06-09T22:01:54.506691 #5731]  WARN -- : +--------------------------------------------------+
W, [2015-06-09T22:01:54.506707 #5731]  WARN -- : |    Want to read about it? http://git.io/vJf3J    |
W, [2015-06-09T22:01:54.506723 #5731]  WARN -- : +--------------------------------------------------+
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- celluloid/logger (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/internals/logging.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/listener.rb:11:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/auto.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:36:in `initialize'
	from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in `new'
	from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in `<top (required)>'
	from /home/jmorgan/bin/awestruct:23:in `load'
	from /home/jmorgan/bin/awestruct:23:in `<main>'
[jmorgan@localhost jaredmorgs.github.io]$ ls
[jmorgan@localhost jaredmorgs.github.io]$ ls -la
total 12
drwxrwxr-x.  3 jmorgan jmorgan 4096 Jun  9 21:29 .
drwxrwxr-x. 12 jmorgan jmorgan 4096 Jun  9 21:28 ..
drwxrwxr-x.  2 jmorgan jmorgan 4096 Jun  9 21:29 .awestruct
```

**Comment by LightGuard** [comment]
Was this before or after you got everything installed and working?

On Tue, Jun 9, 2015 at 6:08 AM, Jared Morgan <notifications@github.com>
wrote:

> I just ran the suggested Awestruct command after getting Awestruct
> installed.
>
> I get this result.
>
> Any idea why I'm seeing this, and how I might fix it?
>
> [jmorgan@localhost jaredmorgs.github.io]$ awestruct --init --framework foundation
> WARN: Unresolved specs during Gem::Specification.reset:
>       bundler (>= 0)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> /home/jmorgan/.gem/ruby/gems/celluloid-0.17.0.pre15/lib/celluloid/deprecate.rb:13: warning: already initialized constant Celluloid::Logger
> /home/jmorgan/.gem/ruby/gems/celluloid-essentials-0.20.0.pre17/lib/celluloid/essentials.rb:27: warning: previous definition of Logger was here
> I, [2015-06-09T22:01:54.506475 #5731]  INFO -- : +--------------------------------------------------+
> I, [2015-06-09T22:01:54.506552 #5731]  INFO -- : |    Celluloid version running now: 0.17.0.pre15   +
> W, [2015-06-09T22:01:54.506590 #5731]  WARN -- : +--------------------------------------------------+
> W, [2015-06-09T22:01:54.506617 #5731]  WARN -- : |     Celluloid is running in BACKPORTED mode.     |
> W, [2015-06-09T22:01:54.506644 #5731]  WARN -- : |   Time to update deprecated code, before v1.0!   |
> W, [2015-06-09T22:01:54.506659 #5731]  WARN -- : +--------------------------------------------------+
> W, [2015-06-09T22:01:54.506676 #5731]  WARN -- : |  Prepare! As of v0.17.5 you can begin updating.  |
> W, [2015-06-09T22:01:54.506691 #5731]  WARN -- : +--------------------------------------------------+
> W, [2015-06-09T22:01:54.506707 #5731]  WARN -- : |    Want to read about it? http://git.io/vJf3J    |
> W, [2015-06-09T22:01:54.506723 #5731]  WARN -- : +--------------------------------------------------+
> /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- celluloid/logger (LoadError)
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/internals/logging.rb:1:in `<top (required)>'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/listener.rb:11:in `<top (required)>'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen.rb:2:in `<top (required)>'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/auto.rb:3:in `<top (required)>'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
>     from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:36:in `initialize'
>     from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in `new'
>     from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in `<top (required)>'
>     from /home/jmorgan/bin/awestruct:23:in `load'
>     from /home/jmorgan/bin/awestruct:23:in `<main>'
> [jmorgan@localhost jaredmorgs.github.io]$ ls
> [jmorgan@localhost jaredmorgs.github.io]$ ls -la
> total 12
> drwxrwxr-x.  3 jmorgan jmorgan 4096 Jun  9 21:29 .
> drwxrwxr-x. 12 jmorgan jmorgan 4096 Jun  9 21:28 ..
> drwxrwxr-x.  2 jmorgan jmorgan 4096 Jun  9 21:29 .awestruct
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/475>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by jaredmorgs** [comment]
This was after successfully compiling the Awestruct packages.

On Fri, 12 Jun 2015 08:07 Jason Porter <notifications@github.com> wrote:

> Was this before or after you got everything installed and working?
>
> On Tue, Jun 9, 2015 at 6:08 AM, Jared Morgan <notifications@github.com>
> wrote:
>
> > I just ran the suggested Awestruct command after getting Awestruct
> > installed.
> >
> > I get this result.
> >
> > Any idea why I'm seeing this, and how I might fix it?
> >
> > [jmorgan@localhost jaredmorgs.github.io]$ awestruct --init --framework
> foundation
> > WARN: Unresolved specs during Gem::Specification.reset:
> > bundler (>= 0)
> > WARN: Clearing out unresolved specs.
> > Please report a bug if this causes problems.
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-0.17.0.pre15/lib/celluloid/deprecate.rb:13:
> warning: already initialized constant Celluloid::Logger
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-essentials-0.20.0.pre17/lib/celluloid/essentials.rb:27:
> warning: previous definition of Logger was here
> > I, [2015-06-09T22:01:54.506475 #5731] INFO -- :
> +--------------------------------------------------+
> > I, [2015-06-09T22:01:54.506552 #5731] INFO -- : | Celluloid version
> running now: 0.17.0.pre15 +
> > W, [2015-06-09T22:01:54.506590 #5731] WARN -- :
> +--------------------------------------------------+
> > W, [2015-06-09T22:01:54.506617 #5731] WARN -- : | Celluloid is running
> in BACKPORTED mode. |
> > W, [2015-06-09T22:01:54.506644 #5731] WARN -- : | Time to update
> deprecated code, before v1.0! |
> > W, [2015-06-09T22:01:54.506659 #5731] WARN -- :
> +--------------------------------------------------+
> > W, [2015-06-09T22:01:54.506676 #5731] WARN -- : | Prepare! As of v0.17.5
> you can begin updating. |
> > W, [2015-06-09T22:01:54.506691 #5731] WARN -- :
> +--------------------------------------------------+
> > W, [2015-06-09T22:01:54.506707 #5731] WARN -- : | Want to read about it?
> http://git.io/vJf3J |
> > W, [2015-06-09T22:01:54.506723 #5731] WARN -- :
> +--------------------------------------------------+
> > /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require':
> cannot load such file -- celluloid/logger (LoadError)
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from
> /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/internals/logging.rb:1:in
> `<top (required)>'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from
> /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/listener.rb:11:in
> `<top (required)>'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen.rb:2:in `<top
> (required)>'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/auto.rb:3:in
> `<top (required)>'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require'
> > from
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:36:in
> `initialize'
> > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> `new'
> > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> `<top (required)>'
> > from /home/jmorgan/bin/awestruct:23:in `load'
> > from /home/jmorgan/bin/awestruct:23:in `<main>'
> > [jmorgan@localhost jaredmorgs.github.io]$ ls
> > [jmorgan@localhost jaredmorgs.github.io]$ ls -la
> > total 12
> > drwxrwxr-x. 3 jmorgan jmorgan 4096 Jun 9 21:29 .
> > drwxrwxr-x. 12 jmorgan jmorgan 4096 Jun 9 21:28 ..
> > drwxrwxr-x. 2 jmorgan jmorgan 4096 Jun 9 21:29 .awestruct
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/awestruct/awestruct/issues/475>.
> >
>
>
>
> --
> Jason Porter
> http://en.gravatar.com/lightguardjp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/475#issuecomment-111289175>
> .
>
-- 

Sent from Mobile.

**Comment by LightGuard** [comment]
I've rebuilt the site, are things looking correct now?

On Tue, Jun 16, 2015 at 1:44 PM, Jared Morgan <notifications@github.com>
wrote:

> This was after successfully compiling the Awestruct packages.
>
> On Fri, 12 Jun 2015 08:07 Jason Porter <notifications@github.com> wrote:
>
> > Was this before or after you got everything installed and working?
> >
> > On Tue, Jun 9, 2015 at 6:08 AM, Jared Morgan <notifications@github.com>
> > wrote:
> >
> > > I just ran the suggested Awestruct command after getting Awestruct
> > > installed.
> > >
> > > I get this result.
> > >
> > > Any idea why I'm seeing this, and how I might fix it?
> > >
> > > [jmorgan@localhost jaredmorgs.github.io]$ awestruct --init --framework
> > foundation
> > > WARN: Unresolved specs during Gem::Specification.reset:
> > > bundler (>= 0)
> > > WARN: Clearing out unresolved specs.
> > > Please report a bug if this causes problems.
> > >
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-0.17.0.pre15/lib/celluloid/deprecate.rb:13:
> > warning: already initialized constant Celluloid::Logger
> > >
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-essentials-0.20.0.pre17/lib/celluloid/essentials.rb:27:
> > warning: previous definition of Logger was here
> > > I, [2015-06-09T22:01:54.506475 #5731] INFO -- :
> > +--------------------------------------------------+
> > > I, [2015-06-09T22:01:54.506552 #5731] INFO -- : | Celluloid version
> > running now: 0.17.0.pre15 +
> > > W, [2015-06-09T22:01:54.506590 #5731] WARN -- :
> > +--------------------------------------------------+
> > > W, [2015-06-09T22:01:54.506617 #5731] WARN -- : | Celluloid is running
> > in BACKPORTED mode. |
> > > W, [2015-06-09T22:01:54.506644 #5731] WARN -- : | Time to update
> > deprecated code, before v1.0! |
> > > W, [2015-06-09T22:01:54.506659 #5731] WARN -- :
> > +--------------------------------------------------+
> > > W, [2015-06-09T22:01:54.506676 #5731] WARN -- : | Prepare! As of
> v0.17.5
> > you can begin updating. |
> > > W, [2015-06-09T22:01:54.506691 #5731] WARN -- :
> > +--------------------------------------------------+
> > > W, [2015-06-09T22:01:54.506707 #5731] WARN -- : | Want to read about
> it?
> > http://git.io/vJf3J |
> > > W, [2015-06-09T22:01:54.506723 #5731] WARN -- :
> > +--------------------------------------------------+
> > > /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> `require':
> > cannot load such file -- celluloid/logger (LoadError)
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from
> >
> /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/internals/logging.rb:1:in
> > `<top (required)>'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from
> > /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/listener.rb:11:in
> > `<top (required)>'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen.rb:2:in
> `<top
> > (required)>'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from
> >
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/auto.rb:3:in
> > `<top (required)>'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require'
> > > from
> >
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:36:in
> > `initialize'
> > > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> > `new'
> > > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> > `<top (required)>'
> > > from /home/jmorgan/bin/awestruct:23:in `load'
> > > from /home/jmorgan/bin/awestruct:23:in `<main>'
> > > [jmorgan@localhost jaredmorgs.github.io]$ ls
> > > [jmorgan@localhost jaredmorgs.github.io]$ ls -la
> > > total 12
> > > drwxrwxr-x. 3 jmorgan jmorgan 4096 Jun 9 21:29 .
> > > drwxrwxr-x. 12 jmorgan jmorgan 4096 Jun 9 21:28 ..
> > > drwxrwxr-x. 2 jmorgan jmorgan 4096 Jun 9 21:29 .awestruct
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/awestruct/awestruct/issues/475>.
> > >
> >
> >
> >
> > --
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/awestruct/awestruct/issues/475#issuecomment-111289175>
> > .
> >
> --
>
> Sent from Mobile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/475#issuecomment-112546517>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by jaredmorgs** [comment]
I'm going to have another go at Awestruct to set up a better web presence
for my jaredmorgs.github.io site. I've got a domain registered now, so I
want to relaunch with a site.

Awestruct really does make lovely sites, so I want it to work. I'm using a
Mac now so perhaps some of the issues I encountered were because of
misconfiguration on my Red Hat laptop.

I'll be in touch if I run into any further issues.

On Tue, 15 Sep 2015 at 11:00 Jason Porter <notifications@github.com> wrote:

> I've rebuilt the site, are things looking correct now?
>
> On Tue, Jun 16, 2015 at 1:44 PM, Jared Morgan <notifications@github.com>
> wrote:
>
> > This was after successfully compiling the Awestruct packages.
> >
> > On Fri, 12 Jun 2015 08:07 Jason Porter <notifications@github.com> wrote:
> >
> > > Was this before or after you got everything installed and working?
> > >
> > > On Tue, Jun 9, 2015 at 6:08 AM, Jared Morgan <notifications@github.com
> >
> > > wrote:
> > >
> > > > I just ran the suggested Awestruct command after getting Awestruct
> > > > installed.
> > > >
> > > > I get this result.
> > > >
> > > > Any idea why I'm seeing this, and how I might fix it?
> > > >
> > > > [jmorgan@localhost jaredmorgs.github.io]$ awestruct --init
> --framework
> > > foundation
> > > > WARN: Unresolved specs during Gem::Specification.reset:
> > > > bundler (>= 0)
> > > > WARN: Clearing out unresolved specs.
> > > > Please report a bug if this causes problems.
> > > >
> > >
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-0.17.0.pre15/lib/celluloid/deprecate.rb:13:
> > > warning: already initialized constant Celluloid::Logger
> > > >
> > >
> >
> /home/jmorgan/.gem/ruby/gems/celluloid-essentials-0.20.0.pre17/lib/celluloid/essentials.rb:27:
> > > warning: previous definition of Logger was here
> > > > I, [2015-06-09T22:01:54.506475 #5731] INFO -- :
> > > +--------------------------------------------------+
> > > > I, [2015-06-09T22:01:54.506552 #5731] INFO -- : | Celluloid version
> > > running now: 0.17.0.pre15 +
> > > > W, [2015-06-09T22:01:54.506590 #5731] WARN -- :
> > > +--------------------------------------------------+
> > > > W, [2015-06-09T22:01:54.506617 #5731] WARN -- : | Celluloid is
> running
> > > in BACKPORTED mode. |
> > > > W, [2015-06-09T22:01:54.506644 #5731] WARN -- : | Time to update
> > > deprecated code, before v1.0! |
> > > > W, [2015-06-09T22:01:54.506659 #5731] WARN -- :
> > > +--------------------------------------------------+
> > > > W, [2015-06-09T22:01:54.506676 #5731] WARN -- : | Prepare! As of
> > v0.17.5
> > > you can begin updating. |
> > > > W, [2015-06-09T22:01:54.506691 #5731] WARN -- :
> > > +--------------------------------------------------+
> > > > W, [2015-06-09T22:01:54.506707 #5731] WARN -- : | Want to read about
> > it?
> > > http://git.io/vJf3J |
> > > > W, [2015-06-09T22:01:54.506723 #5731] WARN -- :
> > > +--------------------------------------------------+
> > > > /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > `require':
> > > cannot load such file -- celluloid/logger (LoadError)
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from
> > >
> >
> /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/internals/logging.rb:1:in
> > > `<top (required)>'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from
> > > /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen/listener.rb:11:in
> > > `<top (required)>'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from /home/jmorgan/.gem/ruby/gems/listen-2.7.12/lib/listen.rb:2:in
> > `<top
> > > (required)>'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from
> > >
> >
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/auto.rb:3:in
> > > `<top (required)>'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in
> > > `require'
> > > > from
> > >
> >
> /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/lib/awestruct/cli/invoker.rb:36:in
> > > `initialize'
> > > > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> > > `new'
> > > > from /home/jmorgan/.gem/ruby/gems/awestruct-0.5.5/bin/awestruct:8:in
> > > `<top (required)>'
> > > > from /home/jmorgan/bin/awestruct:23:in `load'
> > > > from /home/jmorgan/bin/awestruct:23:in `<main>'
> > > > [jmorgan@localhost jaredmorgs.github.io]$ ls
> > > > [jmorgan@localhost jaredmorgs.github.io]$ ls -la
> > > > total 12
> > > > drwxrwxr-x. 3 jmorgan jmorgan 4096 Jun 9 21:29 .
> > > > drwxrwxr-x. 12 jmorgan jmorgan 4096 Jun 9 21:28 ..
> > > > drwxrwxr-x. 2 jmorgan jmorgan 4096 Jun 9 21:29 .awestruct
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/awestruct/awestruct/issues/475>.
> > > >
> > >
> > >
> > >
> > > --
> > > Jason Porter
> > > http://en.gravatar.com/lightguardjp
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/awestruct/awestruct/issues/475#issuecomment-111289175
> >
> > > .
> > >
> > --
> >
> > Sent from Mobile.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/awestruct/awestruct/issues/475#issuecomment-112546517>
> > .
> >
>
>
>
> --
> Jason Porter
> http://en.gravatar.com/lightguardjp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/475#issuecomment-140244194>
> .
>
-- 

Sent from Mobile.

**Comment by LightGuard** [comment]
Are we good to close?

**Comment by jaredmorgs** [comment]
I haven't tried again yet. I'm getting a work Mac so will set it all up on
that. Feel free to close and if there are any issues I can reopen.

On Sat, Sep 26, 2015, 3:56 AM Jason Porter <notifications@github.com> wrote:

> Are we good to close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/475#issuecomment-143305374>
> .
>
-- 

Sent from Mobile.
