### ISSUE TITLE
`site.base_url` doesn't use specified port

### ISSUE THREAD

**Issue by derkork** [awestruct/awestruct#477]
On my machine, port 4242 is blocked by another application, so I modified the rakefile to use another port for the preview:

```
run_awestruct '-d -p 4321'
```

This works, however `site.base_url` is not referring to the specified port, instead it still uses `localhost:4242`. This breaks the CSS references in the default layout template. Overriding it in the `site.yml` file doesn't seem to have any effect, either:

```
name: Project Name
title: Baked with Awestruct
org: Organization
base_url: 'http://localhost:4321/'
```

The links using `site.base_url` still point to `localhost:4242`. 

This happens with the latest github master branch version.

**Comment by LightGuard** [comment]
Which version? Could you please try the latest beta: 0.5.6.beta9?

**Comment by derkork** [comment]
Yes, this happens with 0.5.6.beta9 from the github master branch. I got this in my Gemfile:

```
gem 'awestruct', :git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'
```
You can also see it in the console:

```
Running command: bundle exec awestruct -d -p4321
Generating site: http://localhost:4242
09:09:01 - INFO - LiveReload is waiting for a browser to connect.
Excecuting pipeline...
***************************************************************************
Starting preview server at http://localhost:4321 (Press Ctrl-C to shutdown)
***************************************************************************
```

It listens on 4321 but the output reads "Generating site:  http://localhost:4242". Also `site.base_url` is  `http://localhost:4242`.
