### ISSUE TITLE
Variables site.org and site.com are not evaluated correctly when using JRuby

### ISSUE THREAD

**Issue by mgfeller** [awestruct/awestruct#480]
With JRuby, variables named org and com declared in _config/site.yml are always evaluated to Java::Org and Java::Com, respectively, instead of the declared value. 
Works with Ruby. Other variables work fine. 

Dan suggests in his answer to my newsgroup post that this might be related to top-level namespaces in JRuby.

Incidentally, the variable site.org is declared in the template I used to create a new site (awestruct --init --framework foundation).

**Comment by LightGuard** [comment]
@mojavelinux Do we have a proposed fix for this?

**Comment by mojavelinux** [comment]
I don't know what's causing the name conflict. I haven't looked at the code.

**Comment by LightGuard** [comment]
@mgfeller do have a basic test I can use, or a site?

On Friday, July 24, 2015, Dan Allen <notifications@github.com> wrote:

> I don't know what's causing the name conflict. I haven't looked at the
> code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/480#issuecomment-124779840>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mgfeller** [comment]
@LightGuard you can use https://github.com/mgfeller/aablog-foundation/tree/awestruct-issue-480. The front page shows the evaluated variables. Unfortunately, I don't have a real Ruby test.
