### ISSUE TITLE
Preview fails silently after setting up awestruct on new machine

### ISSUE THREAD

**Issue by zeuzoix** [awestruct/awestruct#481]
I've recently tried to setup my awestruct blog environment on a 64 bit Ubuntu 14.04 machine. I was successfully using awestruct on another machine which is a 32 bit Ubuntu 14.04 machine to edit and publish my blog. 

When I do a rake clean preview I just see the WEBrick service exiting with the following logs. I can't
figure out why it doesn't work.

```
Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/posts/tag/design/index.html
Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/posts/tags/index.html
Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/feed.xml
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
[2015-08-18 09:23:19] INFO  WEBrick 1.3.1
[2015-08-18 09:23:19] INFO  ruby 1.9.3 (2014-11-13) [x86_64-linux]
[2015-08-18 09:23:19] INFO  WEBrick::HTTPServer#start: pid=28700 port=4242
workstation:techeuphoria$
```
I tried cloning asciidoctor.org and preview works on the same machine.

The URL to my blog is https://github.com/zeuzoix/techeuphoria.git

**Comment by LightGuard** [comment]
Are you sure it shut down? The latest awestruct has a feature were it will
generate the page on request in development mode.

On Monday, August 17, 2015, zeuzoix <notifications@github.com> wrote:

> I've recently tried to setup my awestruct blog environment on a 64 bit
> Ubuntu 14.04 machine. When I do a rake clean preview I just see the WEBrick
> service exiting with the following logs
>
> Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/posts/tag/design/index.html
> Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/posts/tags/index.html
> Generating: /home/branch/Conrad/Code/Git/techeuphoria/_site/feed.xml
> ***************************************************************************
> Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
> ***************************************************************************
> [2015-08-18 09:23:19] INFO  WEBrick 1.3.1
> [2015-08-18 09:23:19] INFO  ruby 1.9.3 (2014-11-13) [x86_64-linux]
> [2015-08-18 09:23:19] INFO  WEBrick::HTTPServer#start: pid=28700 port=4242
> workstation:techeuphoria$
>
> I'm not sure why it doesn't work. I tried cloning asciidoctor.org and
> preview works on the same machine.
>
> The URL to my blog is https://github.com/zeuzoix/techeuphoria.git
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/481>.
>


-- 
Sent from Gmail Mobile

**Comment by zeuzoix** [comment]
Yes I could not access it on localhost:4242 from my browser.

**Comment by LightGuard** [comment]
Hmm. Okay, please file a bug

On Monday, August 17, 2015, zeuzoix <notifications@github.com> wrote:

> Yes I could not access it on localhost:4242 from my browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/481#issuecomment-132065742>
> .
>


-- 
Sent from Gmail Mobile

**Comment by zeuzoix** [comment]
I'm not sure of how to file a bug here. I'll move this question to the awestruct talk
