### ISSUE TITLE
Added front matter attributes are not picked up in development mode

### ISSUE THREAD

**Issue by derkork** [awestruct/awestruct#482]
I have a page with front matter like this:

```
---
layout: base
---
```

Now I add a title to the page:

```
---
layout: base
title: Foo
---
````

The addition of the title attribute is not reflected in the output until I restart the development server. However changing an existing title attribute works.  

I am using the latest awestruct directly from the git master branch.

**Comment by LightGuard** [comment]
Which version of awestruct? I thought I'd fixed this :(

On Fri, Sep 4, 2015 at 8:29 AM, Jan Thomä <notifications@github.com> wrote:

> I have a page with front matter like this:
>
> ---
> layout: base
> ---
>
> Now I add a title to the page:
>
> ---
> layout: base
> title: Foo
> ---
>
> The addition of the title attribute is not reflected in the output until I
> restart the development server. However changing an existing title
> attribute works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/482>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
As i wrote, the latest from the master branch here on github. :)

**Comment by LightGuard** [comment]
I doubt I'll be able to write a decent test for this, but please try my master branch for this fix.
