### ISSUE TITLE
Awestruct 0.5.6 looking for nonexistent libfile

### ISSUE THREAD

**Issue by nhr** [awestruct/awestruct#486]
When running Awestruct 0.5.6 on Fedora 22 (ruby 2.2.3p173), I am hitting an error due to a nonexistant libfile path.

As you can see, installing awestruct pulls in the `oga` gem as well:

    $ gem install awestruct
    Fetching: oga-0.3.4.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed oga-0.3.4
    Fetching: awestruct-0.5.6.gem (100%)
    Successfully installed awestruct-0.5.6
    Parsing documentation for oga-0.3.4
    Installing ri documentation for oga-0.3.4
    Parsing documentation for awestruct-0.5.6
    Installing ri documentation for awestruct-0.5.6
    Done installing documentation for oga, awestruct after 3 seconds
    2 gems installed

And when I attempt to run awestruct, it errors out while looking for a file that does not exist in the oga  gem:

    $ awestruct -s
    /home/harrison/.gem/ruby/gems/oga-0.3.4/lib/oga.rb:16:in `require_relative': cannot load such file -- /home/harrison/.gem/ruby/gems/oga-0.3.4/lib/liboga (LoadError)
    	from /home/harrison/.gem/ruby/gems/oga-0.3.4/lib/oga.rb:16:in `<top (required)>'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/lib/awestruct/context_helper.rb:1:in `<top (required)>'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/lib/awestruct/pipeline.rb:2:in `<top (required)>'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/lib/awestruct/engine.rb:7:in `<top (required)>'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/lib/awestruct/cli/generate.rb:1:in `<top (required)>'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:69:in `require'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/lib/awestruct/cli/invoker.rb:36:in `initialize'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/bin/awestruct:8:in `new'
    	from /home/harrison/.gem/ruby/gems/awestruct-0.5.6/bin/awestruct:8:in `<top (required)>'
    	from /home/harrison/bin/awestruct:23:in `load'
    	from /home/harrison/bin/awestruct:23:in `<main>'

Any suggestions?

**Comment by LightGuard** [comment]
Oga has undergone a furry of activity over the past five months, see https://github.com/YorickPeterse/oga/blob/master/CHANGELOG.md. I'm working on updating the dependency on my master branch, which you could use to test, but I'm hitting a failing test which I'm trying to fix currently. I will update as soon as I have more progress.

**Comment by nhr** [comment]
Thank you! As a workaround, I found that by copying:

   ~/ .gem/ruby/gems/oga-0.3.4/ext/c/liboga.so

to:

    ~/.gem/ruby/gems/oga-0.3.4/lib/

That the system works correctly.

**Comment by LightGuard** [comment]
I'm pretty sure this is fixed in a more current version of oga. There's also quite a few perf improvements in version 1.3 of oga, which is always good for us :)

**Comment by LightGuard** [comment]
Please try my master branch and let me know. Also note #487 if you're using 960 or blueprint.

**Comment by nhr** [comment]
I won't be able to do this today but I will run some tests on Monday if that's still helpful.

**Comment by LightGuard** [comment]
Yes, still helpful. I'll be travelling later today, so I won't be doing much more work on this today.

**Comment by LightGuard** [comment]
@nhr Were you able to get to running any tests for this?

**Comment by nhr** [comment]
Yes. I removed the hand-copied .so file from oga v0.3.4 and uninstalled awestruct, then built and installed the awestruct gem from your master branch. I see that it pulled in oga v1.3.1. When I ran your version of awestruct, it worked without errors.

**Comment by LightGuard** [comment]
Great! I'll merge in my branch then.

On Wed, Sep 30, 2015 at 3:39 PM, N. Harrison Ripps <notifications@github.com
> wrote:

> Yes. I removed the hand-copied .so file from oga v0.3.4 and uninstalled
> awestruct, then built and installed the awestruct gem from your master
> branch. I see that it pulled in oga v1.3.1. When I ran your version of
> awestruct, it worked without errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/486#issuecomment-144517052>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp
