### ISSUE TITLE
Issue with the latest update from github

### ISSUE THREAD

**Issue by derkork** [awestruct/awestruct#489]
Whenever I want to generate a HTML file from a html.haml file I get this error:

```
e /Users/j.thomae/devel/ruby/typescript-test/index.html.haml
[2015-10-06 16:20:02] ERROR NoMethodError: undefined method `split' for 372:Fixnum
        /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:99:in `block in service'
        /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:91:in `each'
        /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:91:in `service'
        /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

Gemfile is:

```
source 'https://rubygems.org'                             # This tells Bundler where to look for gems

gem 'awestruct', :git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'
gem 'compass', '>= 1.0.1'
gem 'typescript-node'
```

so it's really just minimum dependencies. Ruby is 2.1.5. Creating typescript using my custom pipeline seems to work.

**Comment by LightGuard** [comment]
Do you have the same issue with the latest released version?

On Tuesday, October 6, 2015, Jan Thomä <notifications@github.com> wrote:

> Whenever I want to generate a HTML file from a html.haml file I get this
> error:
>
> e /Users/j.thomae/devel/ruby/typescript-test/index.html.haml
> [2015-10-06 16:20:02] ERROR NoMethodError: undefined method `split' for 372:Fixnum
>         /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:99:in `block in service'
>         /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:91:in `each'
>         /Users/j.thomae/.rvm/gems/ruby-2.1.5@test/gems/rack-1.6.2/lib/rack/handler/webrick.rb:91:in `service'
>         /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
>         /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
>         /Users/j.thomae/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
>
> Gemfile is:
>
> source 'https://rubygems.org'                             # This tells Bundler where to look for gems
>
> gem 'awestruct', :git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'
> gem 'compass', '>= 1.0.1'
> gem 'typescript-node'
>
> so it's really just minimum dependencies. Ruby is 2.1.5. Creating
> typescript using my custom pipeline seems to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/489>.
>


-- 
Sent from Gmail Mobile

**Comment by derkork** [comment]
I downgraded to 0.5.6 (the released version) and this is working. So it's only in the Github trunk.

**Comment by LightGuard** [comment]
Okay, great! Thanks for replying. That gives me a much better idea of what
to look for.

On Tuesday, October 6, 2015, Jan Thomä <notifications@github.com> wrote:

> I downgraded to 0.5.6 (the released version) and this is working. So it's
> only in the Github trunk.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/489#issuecomment-145876043>
> .
>


-- 
Sent from Gmail Mobile

**Comment by derkork** [comment]
Of course. Let me know if you need anything else.
