### ISSUE TITLE
Latest github master branch version breaks zurb 4.x support

### ISSUE THREAD

**Issue by derkork** [awestruct/awestruct#495]
We have a project running on Zurb 4.x. With the latest version from github's master branch (0.5.7.RC3) the foundation import in our scss files can no longer be resolved:

```
@import "foundation";
```
```
While processing file /Users/kork/devel/ruby/ancientlightstudios.com/stylesheets/app.scss
An error occurred: File to import not found or unreadable: foundation.
Load path: /Users/kork/devel/ruby/ancientlightstudios.com/stylesheets
/Users/kork/devel/ruby/ancientlightstudios.com/stylesheets/app.scss:8
/Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:67:in `rescue in import'
/Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:45:in `import'
/Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:28:in `imported_file'
/Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:37:in `css_import?'
```

When switching to 0.5.6 stable, the issue disappears.

**Comment by LightGuard** [comment]
Add `require "zurb-foundation"` to your _ext/pipeline file and it should
work correctly with HEAD.

On Wed, Oct 21, 2015 at 8:28 AM, Jan Thomä <notifications@github.com> wrote:

> We have a project running on Zurb 4.x. With the latest version from
> github's master branch (0.5.7.RC3) the foundation import in our scss files
> can no longer be resolved:
>
> @import "foundation";
>
> While processing file /Users/kork/devel/ruby/ancientlightstudios.com/stylesheets/app.scss
> An error occurred: File to import not found or unreadable: foundation.
> Load path: /Users/kork/devel/ruby/ancientlightstudios.com/stylesheets
> /Users/kork/devel/ruby/ancientlightstudios.com/stylesheets/app.scss:8
> /Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:67:in <http://ancientlightstudios.com/stylesheets/Users/kork/devel/ruby/ancientlightstudios.com/stylesheets/app.scss:8/Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:67:in> `rescue in import'
> /Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:45:in `import'
> /Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:28:in `imported_file'
> /Users/kork/.rvm/gems/ruby-2.1.5/gems/sass-3.4.19/lib/sass/tree/import_node.rb:37:in `css_import?'
>
> When switching to 0.5.6 stable, the issue disappears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
The

```
require "zurb-foundation";
```

entry is already present in `pipeline.rb` (it always was). So that isn't the cause of the issue.

**Comment by LightGuard** [comment]
Is it also in your Gemfile?

On Wed, Oct 21, 2015 at 9:41 AM, Jan Thomä <notifications@github.com> wrote:

> The
>
> require "zurb-foundation";
>
> entry is already present in pipeline.rb (it always was). So that isn't
> the cause of the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495#issuecomment-149806203>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
Yes it is. 

When I change the awestruct version in the Gemfile to 0.5.6 it works, when i change it to github/master, it stops working. So it must be something about the github master version of awestruct that is breaking it.

Here's my gemfile

```
gem 'awestruct', '0.5.6'
#:git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'
gem 'rake', '>= 0.9.2' # Needed for the Rakefile to work
gem 'asciidoctor', '>= 0.1.3' # If using AsciiDoc syntax, need 0.1.1 for Header support
gem 'asciidoctor-pdf', :git => 'git://github.com/asciidoctor/asciidoctor-pdf.git', :branch => 'master' # pdf generation
gem 'rmagick'
gem 'thread_safe'
gem 'coderay'
gem 'pygments.rb'
gem 'zurb-foundation'
gem 'redcarpet', '~> 3.0.0'                              # markdown inside haml
```

**Comment by LightGuard** [comment]
Hm. Okay.... is your site available to use for testing?

On Wed, Oct 21, 2015 at 9:45 AM, Jan Thomä <notifications@github.com> wrote:

> Yes it is.
>
> When I change the awestruct version in the Gemfile to 0.5.6 it works, when
> i change it to github/master, it stops working. So it must be something
> about the github master version of awestruct that is breaking it.
>
> Here's my gemfile
>
> gem 'awestruct', '0.5.6'
> #:git => 'git://github.com/awestruct/awestruct.git', :branch => 'master'
> gem 'rake', '>= 0.9.2' # Needed for the Rakefile to work
> gem 'asciidoctor', '>= 0.1.3' # If using AsciiDoc syntax, need 0.1.1 for Header support
> gem 'asciidoctor-pdf', :git => 'git://github.com/asciidoctor/asciidoctor-pdf.git', :branch => 'master' # pdf generation
> gem 'rmagick'
> gem 'thread_safe'
> gem 'coderay'
> gem 'pygments.rb'
> gem 'zurb-foundation'
> gem 'redcarpet', '~> 3.0.0'                              # markdown inside haml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495#issuecomment-149806866>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
It's in a private repository. I can send you a zip of the site via 
dropbox if that helps.

**Comment by LightGuard** [comment]
Well, that would work, but better would be if you had a simpler site that
recreates the issue we could use for testing.

On Wed, Oct 21, 2015 at 10:46 AM, Jan Thomä <notifications@github.com>
wrote:

> It's in a private repository. I can send you a zip of the site via
> dropbox if that helps.
>
> > Jason Porter <mailto:notifications@github.com>
> > 21 Oct 2015 09:53
> > Hm. Okay.... is your site available to use for testing?
> >
> > On Wed, Oct 21, 2015 at 9:45 AM, Jan Thomä <notifications@github.com>
> > wrote:
> >
> > > Yes it is.
> > >
> > > When I change the awestruct version in the Gemfile to 0.5.6 it
> > works, when
> > > i change it to github/master, it stops working. So it must be something
> > > about the github master version of awestruct that is breaking it.
> > >
> > > Here's my gemfile
> > >
> > > gem 'awestruct', '0.5.6'
> > > #:git => 'git://github.com/awestruct/awestruct.git', :branch =>
> 'master'
> > > gem 'rake', '>= 0.9.2' # Needed for the Rakefile to work
> > > gem 'asciidoctor', '>= 0.1.3' # If using AsciiDoc syntax, need 0.1.1
> > for Header support
> > > gem 'asciidoctor-pdf', :git =>
> > 'git://github.com/asciidoctor/asciidoctor-pdf.git', :branch =>
> > 'master' # pdf generation
> > > gem 'rmagick'
> > > gem 'thread_safe'
> > > gem 'coderay'
> > > gem 'pygments.rb'
> > > gem 'zurb-foundation'
> > > gem 'redcarpet', '~> 3.0.0' # markdown inside haml
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/awestruct/awestruct/issues/495#issuecomment-149806866>
> > > .
> > >
> >
> >
> >
> > --
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/awestruct/awestruct/issues/495#issuecomment-149808321>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495#issuecomment-149823563>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
Makes sense. I'll try to come up with a simple example and put it on github.

**Comment by LightGuard** [comment]
Thank you

On Wed, Oct 21, 2015 at 10:59 AM, Jan Thomä <notifications@github.com>
wrote:

> Makes sense. I'll try to come up with a simple example and put it on
> github.
>
> > Jason Porter <mailto:notifications@github.com>
> > 21 Oct 2015 10:54
>
> > Well, that would work, but better would be if you had a simpler site that
> > recreates the issue we could use for testing.
> >
> > On Wed, Oct 21, 2015 at 10:46 AM, Jan Thomä <notifications@github.com>
> > wrote:
> >
> > > It's in a private repository. I can send you a zip of the site via
> > > dropbox if that helps.
> > >
> > > > Jason Porter <mailto:notifications@github.com>
> > > > 21 Oct 2015 09:53
> > > > Hm. Okay.... is your site available to use for testing?
> > > >
> > > > On Wed, Oct 21, 2015 at 9:45 AM, Jan Thomä <notifications@github.com
> >
> > > > wrote:
> > > >
> > > > > Yes it is.
> > > > >
> > > > > When I change the awestruct version in the Gemfile to 0.5.6 it
> > > > works, when
> > > > > i change it to github/master, it stops working. So it must be
> > something
> > > > > about the github master version of awestruct that is breaking it.
> > > > >
> > > > > Here's my gemfile
> > > > >
> > > > > gem 'awestruct', '0.5.6'
> > > > > #:git => 'git://github.com/awestruct/awestruct.git', :branch =>
> > > 'master'
> > > > > gem 'rake', '>= 0.9.2' # Needed for the Rakefile to work
> > > > > gem 'asciidoctor', '>= 0.1.3' # If using AsciiDoc syntax, need
> 0.1.1
> > > > for Header support
> > > > > gem 'asciidoctor-pdf', :git =>
> > > > 'git://github.com/asciidoctor/asciidoctor-pdf.git', :branch =>
> > > > 'master' # pdf generation
> > > > > gem 'rmagick'
> > > > > gem 'thread_safe'
> > > > > gem 'coderay'
> > > > > gem 'pygments.rb'
> > > > > gem 'zurb-foundation'
> > > > > gem 'redcarpet', '~> 3.0.0' # markdown inside haml
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > > <
> > >
> > https://github.com/awestruct/awestruct/issues/495#issuecomment-149806866
> >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Jason Porter
> > > > http://en.gravatar.com/lightguardjp
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> > https://github.com/awestruct/awestruct/issues/495#issuecomment-149808321
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/awestruct/awestruct/issues/495#issuecomment-149823563>
> > > .
> > >
> >
> >
> >
> > --
> > Jason Porter
> > http://en.gravatar.com/lightguardjp
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/awestruct/awestruct/issues/495#issuecomment-149825685>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495#issuecomment-149826544>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by derkork** [comment]
I created a minimal example. See https://github.com/derkork/awestruct-issue-495 .

**Comment by LightGuard** [comment]
Excellent, thank you!

On Wednesday, October 21, 2015, Jan Thomä <notifications@github.com> wrote:

> I created a minimal example. See
> https://github.com/derkork/awestruct-issue-495 .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/495#issuecomment-149992352>
> .
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
Fixed with latest HEAD.
