### ISSUE TITLE
Setting source dir overwrites output dir

### ISSUE THREAD

**Issue by rtyler** [awestruct/awestruct#496]
If I use both a custom output dir and a source dir, the order in which those options are declared changes the behavior of the CLI.

This looks to me to be a simple bug of unintended consequences [with this line in options.rb](https://github.com/awestruct/awestruct/blob/master/lib/awestruct/cli/options.rb#L135)

**Comment by LightGuard** [comment]
Care to submit a patch? I'd say leave output_dir uninitalized until the end
if it isn't set set it to source_dir/_site and then remove that currently
offending line. Make sense?

On Saturday, October 24, 2015, R. Tyler Croy <notifications@github.com>
wrote:

> If I use both a custom output dir and a source dir, the order in which
> those options are declared changes the behavior of the CLI.
>
> This looks to me to be a simple bug of unintended consequences with this
> line in options.rb
> <https://github.com/awestruct/awestruct/blob/master/lib/awestruct/cli/options.rb#L135>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/496>.
>


-- 
Sent from Gmail Mobile
