### ISSUE TITLE
Partial helper won't work if the CLI is used outside the content directory

### ISSUE THREAD

**Issue by rtyler** [awestruct/awestruct#497]
When using `--source-dir`, the Partial helper simply lists out "Could not find _partials/footer.html.haml" if the `awestruct` CLI is used with a working directory that is not the directory specified in `--source-dir`

My hunch is that this is due to [the Partial class](https://github.com/awestruct/awestruct/blob/master/lib/awestruct/extensions/partial.rb#L6) not generating an absolute path or anything like that.

**Comment by LightGuard** [comment]
Wow, that is a really obscure bug.

On Sun, Oct 25, 2015 at 5:36 AM, R. Tyler Croy <notifications@github.com>
wrote:

> When using --source-dir, the Partial helper simply lists out "Could not
> find _partials/footer.html.haml" if the awestruct CLI is used with a
> working directory that is not the directory specified in --source-dir
>
> My hunch is that this is due to the Partial class
> <https://github.com/awestruct/awestruct/blob/master/lib/awestruct/extensions/partial.rb#L6>
> not generating an absolute path or anything like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/497>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by rtyler** [comment]
Yeah it is, I'm still waiting for its mixtape to be released on vinyl though

**Comment by LightGuard** [comment]
Do you have a sample I can try, or would you mind verifying with commit

**Comment by LightGuard** [comment]
Fix verified locally.
