### ISSUE TITLE
Error in Guard:Module when running 

### ISSUE THREAD

**Issue by xcoulon** [awestruct/awestruct#508]
with both awestruct 05.6. and 0.5.7.RC2, I have the following error when running `bundle exec awestruct -d` :

```
Using profile: development
Generating site: http://localhost:4242
Excecuting pipeline...
undefined method `init' for Guard:Module
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/auto.rb:21:in `run'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:144:in `invoke_auto'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:53:in `invoke!'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/bin/awestruct:9:in `<top (required)>'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `load'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `<main>'

```

The Gemfile has the following content:

```
source 'https://rubygems.org'

# Main site dependencies
gem 'awestruct', '0.5.7.RC2'

# use Patternfly for the layout
gem 'patternfly-sass', '2.9.0'

# Enable a Markdown gem (only rdiscount seems to work w/ the site):
gem 'rdiscount', '~> 2.0.7', :platforms => [:ruby]

# To enable guard and livereload (is C native thus not available on windows. Commented out for now)
gem 'guard'
gem 'guard-livereload'
```

Note that the website is built correctly and using the `--no-livereload` switch, the error disappears.

**Comment by LightGuard** [comment]
That's been fixed in HEAD for a few weeks.

On Monday, February 1, 2016, Xavier Coulon <notifications@github.com> wrote:

> with both awestruct 05.6. and 0.5.7.RC2, I have the following error when
> running bundle exec awestruct -d :
>
> Using profile: development
> Generating site: http://localhost:4242
> Excecuting pipeline...
> undefined method `init' for Guard:Module
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/auto.rb:21:in `run'
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:144:in `invoke_auto'
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/lib/awestruct/cli/invoker.rb:53:in `invoke!'
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/awestruct-0.5.7.RC2/bin/awestruct:9:in `<top (required)>'
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `load'
> /Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bin/awestruct:23:in `<main>'
>
>
> The Gemfile has the following content:
>
> source 'https://rubygems.org'
>
> # Main site dependencies
> gem 'awestruct', '0.5.7.RC2'
>
> # use Patternfly for the layout
> gem 'patternfly-sass', '2.9.0'
>
> # Enable a Markdown gem (only rdiscount seems to work w/ the site):
> gem 'rdiscount', '~> 2.0.7', :platforms => [:ruby]
>
> # To enable guard and livereload (is C native thus not available on windows. Commented out for now)
> gem 'guard'
> gem 'guard-livereload'
>
> Note that the website is built correctly and using the --no-livereload
> switch, the error disappears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/508>.
>


-- 
Sent from Gmail Mobile

**Comment by xcoulon** [comment]
@LightGuard awesome ! do you plan to release an RC3 anytime soon ?

**Comment by LightGuard** [comment]
I have some documentation to do, maybe some extra logging we're discussing
adding, but besides that it should be complete.

On Mon, Feb 1, 2016 at 2:03 PM, Xavier Coulon <notifications@github.com>
wrote:

> @LightGuard <https://github.com/LightGuard> awesome ! do you plan to
> release an RC3 anytime soon ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/508#issuecomment-178188861>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp
