### ISSUE TITLE
awestruct --init require a git repo

### ISSUE THREAD

**Issue by aslakknutsen** [awestruct/awestruct#519]
```
mkdir test-a && cd test-a
awestruct --init -f foundation
```

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by LightGuard** [comment]
Thoughts on where this is happening? I'll have to dig for it.
