### ISSUE TITLE
awestruct quietly exits when there are ERB errors in site.yml

### ISSUE THREAD

**Issue by rtyler** [awestruct/awestruct#538]
Imagine a broken/incorrect `site.yml` which has some ERB syntax errors in it.

By default the `awestruct` CLI quietly exits :frowning: 

A slight improvement would be to simply re-raise [the caught error](https://github.com/awestruct/awestruct/blob/master/lib/awestruct/cli/invoker.rb#L87) in `awestruct/cli/invoker#invoke!`

Not sure how best to raise the ERB failure though

**Comment by LightGuard** [comment]
Have you looked at the `.awestruct/error.log` file?

**Comment by LightGuard** [comment]
All errors are logged in the `.awestruct/error.log` file
