### ISSUE TITLE
Post date doesn't correctly support 2020+ dates

### ISSUE THREAD

**Issue by jamezp** [awestruct/awestruct#547]
I'm not a Ruby expert, but it looks like the date for posts [hard-codes a `201x`](https://github.com/awestruct/awestruct/blob/master/lib/awestruct/extensions/posts.rb#L42-L45) date meaning anything from 2020 on doesn't end up with a nice path like `2020/01/03/My-Blog` and instead ends up with `2020/01/03/2020-01-03-My-Blog`.

**Comment by zbynek** [comment]
Thanks. A fix should land in the next 0.6 alpha release, probably next week.

**Comment by zbynek** [comment]
0.6.0alpha4 is out, please check

**Comment by jamezp** [comment]
Unfortunately I'm not able to confirm it works. I can't wildfly.org to build with this upgrade, though it's not related to this change at all. I'll see if I can't figure out why this is at some point.
