### ISSUE TITLE
asciidocotor dependecy fix to 1.5.x, what is with 2.x support? 

### ISSUE THREAD

**Issue by a4z** [awestruct/awestruct#554]
the main reason why I am using awestruct is the native ascidoctor support

but I can not specify a newer version than 1.5.8 in the Gemfile

any special reason 2.x is not supported?

**Comment by zbynek** [comment]
I fixed that in `master`, you can put this to your Gemfile and check if it's compatible:
```
gem 'awestruct', git: 'https://github.com/awestruct/awestruct.git'
```

**Comment by a4z** [comment]
thanks! will do as soon as I find the time, probably upcoming weekend

**Comment by a4z** [comment]
this seems to work, thanks! 

but I do get a strange warning message ...
```
Fetching https://github.com/awestruct/awestruct.git
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/awestruct-acd80111f53f/awestruct.gemspec:15.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/awestruct-acd80111f53f/awestruct.gemspec:22.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
```

may I ask you, @zbynek , what is your (maintenance/develomemnt) plan with awestruct?
I was already thinking about using some other framework, but now seeing that there is somesing happen, I would like to keep it because so far it worked.
but is there a danger that soon awestruct will be unmaintained again, or how do you think the next future of the project will look like?

**Comment by zbynek** [comment]
I think the amount of work needed to maintain the status quo is pretty low and I'm willing to continue with that on a best-effort basis (no promises on the timeline). I don't plan to implement any major features though. Maybe @LightGuard has some more exciting development plans.
